---
title: "EjemploRyPython"
author: "Sandra Gutiérrez"
date: "2023-09-28"
output: html_document
---

##Reticulate

```{r}
library(reticulate)
#use_python("/Users/HP/anaconda3/python")
os <- import("os")
os$listdir(".")
```

```{r}
source_python("add.py")
suma(2,6)
```


```{r}
np <- import("numpy", convert = FALSE)
x <- np$array(c(1:4))
#Objeto de Python
sum <- x$cumsum()
print(sum)
#Objeto de R
py_to_r(sum)
```

##Ayuda

```{r}
help(py_to_r)
py_help(os$chdir)
```



```{r}
m <- np_array(c(1:10), order="C")
m
datos <- iris
head(datos)
datos_py <- r_to_py(datos)
```


```{python}
import numpy as np
import pandas as pd

#Puedes acceder a cualquier cosa de R a traves del siguiente código

r.datos_py.head()
```


##Sparse Matrix

```{r}
library(Matrix)
N <- 6
set.seed(123)
sparse_mat <- sparseMatrix(
  i = sample(N,N, replace=F),
  j = sample(N,N, replace=F),
  x = runif(N),
  dims = c(N,N)
)
sparse_mat
sparse_mat_py <- r_to_py(sparse_mat)
```


```{python}
r.sparse_mat_py
```

```{r}
py_to_r(sparse_mat_py)
```



